name: Build latest
on:
  push:
    branches:
      - develop
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Run after merge
        run: echo "Code was merged into develop. Proceeding with LaTeX build."
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          pre_compile: "tlmgr update --self && tlmgr update --all"
          post_compile: "latexmk -c"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-pdf-${{ github.sha }}
          path: main.pdf
          if-no-files-found: error
          retention-days: 7
